version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend
    ports:
      - "8080:80"
  backend:
    build: .
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    links:
      - database
  database:
    image: mysql
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
